[project]
site_name = "Entangled"
site_url = "https://entangled.github.io/"
site_discription = """Documentation for Entangled, the literate programming toolbox."""
site_author = "Johan Hidding"
copyright = "&copy; 2018-2026 Johan Hidding, Netherlands eScience Center"
extra_css = ["stylesheets/extra.css"]

nav = [ "index.md", "examples.md",
	{"Configuration"   = ["markup.md", "templates.md"]},
	{"Weavers"         = ["mkdocs.md", "quarto.md", "typst.md", "pandoc.md", "weaver-wishlist.md"]},
	{"Hooks" 	       = ["hooks.md", "quarto_attributes.md"]},
	{"Workflows"       = ["workflows.md", "build-hook.md"]},
	{"Troubleshooting" = ["git.md"]},
	{"Resources"       = ["manual.md", "ieee-escience-paper.md"]} ]

[project.markdown_extensions.attr_list]
[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.md_in_html]

[project.plugins.bibtex]
bib_file = "refs.bib"
